-- ============================================================================
-- WC26 FAN VOTE — MIGRATION: seed the full cosmetics catalogue (144 items)
-- ============================================================================
-- The frontend (js/customization.js) generates 144 cosmetics from
-- CUST_TEAMS x WC26_THEMES x CUST_CATS. For ownership to PERSIST, every one of
-- them must exist as a row in public.cosmetics whose `code` matches the frontend
-- item id (e.g. 'France_nameplate_France', 'wc26_banner_NeonGoal'). The app maps
-- code -> uuid on load, calls buy_cosmetic(uuid) / equip_cosmetic(uuid), and
-- reads ownership back from public.user_cosmetics.
--
-- Idempotent: safe to re-run (on conflict (code) do nothing). Leaves the 6
-- example rows from the baseline schema untouched (their codes differ).
-- ============================================================================

insert into public.cosmetics
  (code, name, theme_name, slot, rarity, team_code, is_animated, colors, price_fc)
values
 ('France_avatar_France','France Avatar','France','avatar','common','France',false,ARRAY['#1B3A8C','#EF4135','#FFFFFF']::text[],600),
 ('France_avatar_anim_France','France Animated Avatar','France','avatar','epic','France',true,ARRAY['#1B3A8C','#EF4135','#FFFFFF']::text[],1200),
 ('France_decoration_France','France Decoration','France','decoration','rare','France',false,ARRAY['#1B3A8C','#EF4135','#FFFFFF']::text[],900),
 ('France_decoration_anim_France','France Animated Decoration','France','decoration','legendary','France',true,ARRAY['#1B3A8C','#EF4135','#FFFFFF']::text[],1800),
 ('France_nameplate_France','France Name Plate','France','nameplate','rare','France',false,ARRAY['#1B3A8C','#EF4135','#FFFFFF']::text[],750),
 ('France_banner_France','France Banner','France','banner','epic','France',false,ARRAY['#1B3A8C','#EF4135','#FFFFFF']::text[],1500),
 ('Brazil_avatar_Brazil','Brazil Avatar','Brazil','avatar','common','Brazil',false,ARRAY['#009C3B','#FFDF00','#1B5E20']::text[],600),
 ('Brazil_avatar_anim_Brazil','Brazil Animated Avatar','Brazil','avatar','epic','Brazil',true,ARRAY['#009C3B','#FFDF00','#1B5E20']::text[],1200),
 ('Brazil_decoration_Brazil','Brazil Decoration','Brazil','decoration','rare','Brazil',false,ARRAY['#009C3B','#FFDF00','#1B5E20']::text[],900),
 ('Brazil_decoration_anim_Brazil','Brazil Animated Decoration','Brazil','decoration','legendary','Brazil',true,ARRAY['#009C3B','#FFDF00','#1B5E20']::text[],1800),
 ('Brazil_nameplate_Brazil','Brazil Name Plate','Brazil','nameplate','rare','Brazil',false,ARRAY['#009C3B','#FFDF00','#1B5E20']::text[],750),
 ('Brazil_banner_Brazil','Brazil Banner','Brazil','banner','epic','Brazil',false,ARRAY['#009C3B','#FFDF00','#1B5E20']::text[],1500),
 ('England_avatar_England','England Avatar','England','avatar','common','England',false,ARRAY['#CF142B','#1D3D8F','#FFFFFF']::text[],600),
 ('England_avatar_anim_England','England Animated Avatar','England','avatar','epic','England',true,ARRAY['#CF142B','#1D3D8F','#FFFFFF']::text[],1200),
 ('England_decoration_England','England Decoration','England','decoration','rare','England',false,ARRAY['#CF142B','#1D3D8F','#FFFFFF']::text[],900),
 ('England_decoration_anim_England','England Animated Decoration','England','decoration','legendary','England',true,ARRAY['#CF142B','#1D3D8F','#FFFFFF']::text[],1800),
 ('England_nameplate_England','England Name Plate','England','nameplate','rare','England',false,ARRAY['#CF142B','#1D3D8F','#FFFFFF']::text[],750),
 ('England_banner_England','England Banner','England','banner','epic','England',false,ARRAY['#CF142B','#1D3D8F','#FFFFFF']::text[],1500),
 ('Argentina_avatar_Argentina','Argentina Avatar','Argentina','avatar','common','Argentina',false,ARRAY['#75AADB','#FFFFFF','#F6B40E']::text[],600),
 ('Argentina_avatar_anim_Argentina','Argentina Animated Avatar','Argentina','avatar','epic','Argentina',true,ARRAY['#75AADB','#FFFFFF','#F6B40E']::text[],1200),
 ('Argentina_decoration_Argentina','Argentina Decoration','Argentina','decoration','rare','Argentina',false,ARRAY['#75AADB','#FFFFFF','#F6B40E']::text[],900),
 ('Argentina_decoration_anim_Argentina','Argentina Animated Decoration','Argentina','decoration','legendary','Argentina',true,ARRAY['#75AADB','#FFFFFF','#F6B40E']::text[],1800),
 ('Argentina_nameplate_Argentina','Argentina Name Plate','Argentina','nameplate','rare','Argentina',false,ARRAY['#75AADB','#FFFFFF','#F6B40E']::text[],750),
 ('Argentina_banner_Argentina','Argentina Banner','Argentina','banner','epic','Argentina',false,ARRAY['#75AADB','#FFFFFF','#F6B40E']::text[],1500),
 ('Spain_avatar_Spain','Spain Avatar','Spain','avatar','common','Spain',false,ARRAY['#C60B1E','#FFC400','#7A0512']::text[],600),
 ('Spain_avatar_anim_Spain','Spain Animated Avatar','Spain','avatar','epic','Spain',true,ARRAY['#C60B1E','#FFC400','#7A0512']::text[],1200),
 ('Spain_decoration_Spain','Spain Decoration','Spain','decoration','rare','Spain',false,ARRAY['#C60B1E','#FFC400','#7A0512']::text[],900),
 ('Spain_decoration_anim_Spain','Spain Animated Decoration','Spain','decoration','legendary','Spain',true,ARRAY['#C60B1E','#FFC400','#7A0512']::text[],1800),
 ('Spain_nameplate_Spain','Spain Name Plate','Spain','nameplate','rare','Spain',false,ARRAY['#C60B1E','#FFC400','#7A0512']::text[],750),
 ('Spain_banner_Spain','Spain Banner','Spain','banner','epic','Spain',false,ARRAY['#C60B1E','#FFC400','#7A0512']::text[],1500),
 ('Germany_avatar_Germany','Germany Avatar','Germany','avatar','common','Germany',false,ARRAY['#111111','#DD0000','#FFCE00']::text[],600),
 ('Germany_avatar_anim_Germany','Germany Animated Avatar','Germany','avatar','epic','Germany',true,ARRAY['#111111','#DD0000','#FFCE00']::text[],1200),
 ('Germany_decoration_Germany','Germany Decoration','Germany','decoration','rare','Germany',false,ARRAY['#111111','#DD0000','#FFCE00']::text[],900),
 ('Germany_decoration_anim_Germany','Germany Animated Decoration','Germany','decoration','legendary','Germany',true,ARRAY['#111111','#DD0000','#FFCE00']::text[],1800),
 ('Germany_nameplate_Germany','Germany Name Plate','Germany','nameplate','rare','Germany',false,ARRAY['#111111','#DD0000','#FFCE00']::text[],750),
 ('Germany_banner_Germany','Germany Banner','Germany','banner','epic','Germany',false,ARRAY['#111111','#DD0000','#FFCE00']::text[],1500),
 ('Morocco_avatar_Morocco','Morocco Avatar','Morocco','avatar','common','Morocco',false,ARRAY['#C1272D','#006233','#0E3B27']::text[],600),
 ('Morocco_avatar_anim_Morocco','Morocco Animated Avatar','Morocco','avatar','epic','Morocco',true,ARRAY['#C1272D','#006233','#0E3B27']::text[],1200),
 ('Morocco_decoration_Morocco','Morocco Decoration','Morocco','decoration','rare','Morocco',false,ARRAY['#C1272D','#006233','#0E3B27']::text[],900),
 ('Morocco_decoration_anim_Morocco','Morocco Animated Decoration','Morocco','decoration','legendary','Morocco',true,ARRAY['#C1272D','#006233','#0E3B27']::text[],1800),
 ('Morocco_nameplate_Morocco','Morocco Name Plate','Morocco','nameplate','rare','Morocco',false,ARRAY['#C1272D','#006233','#0E3B27']::text[],750),
 ('Morocco_banner_Morocco','Morocco Banner','Morocco','banner','epic','Morocco',false,ARRAY['#C1272D','#006233','#0E3B27']::text[],1500),
 ('Portugal_avatar_Portugal','Portugal Avatar','Portugal','avatar','common','Portugal',false,ARRAY['#006600','#FF0000','#003300']::text[],600),
 ('Portugal_avatar_anim_Portugal','Portugal Animated Avatar','Portugal','avatar','epic','Portugal',true,ARRAY['#006600','#FF0000','#003300']::text[],1200),
 ('Portugal_decoration_Portugal','Portugal Decoration','Portugal','decoration','rare','Portugal',false,ARRAY['#006600','#FF0000','#003300']::text[],900),
 ('Portugal_decoration_anim_Portugal','Portugal Animated Decoration','Portugal','decoration','legendary','Portugal',true,ARRAY['#006600','#FF0000','#003300']::text[],1800),
 ('Portugal_nameplate_Portugal','Portugal Name Plate','Portugal','nameplate','rare','Portugal',false,ARRAY['#006600','#FF0000','#003300']::text[],750),
 ('Portugal_banner_Portugal','Portugal Banner','Portugal','banner','epic','Portugal',false,ARRAY['#006600','#FF0000','#003300']::text[],1500),
 ('Netherlands_avatar_Netherlands','Netherlands Avatar','Netherlands','avatar','common','Netherlands',false,ARRAY['#AE1C28','#21468B','#FF7F00']::text[],600),
 ('Netherlands_avatar_anim_Netherlands','Netherlands Animated Avatar','Netherlands','avatar','epic','Netherlands',true,ARRAY['#AE1C28','#21468B','#FF7F00']::text[],1200),
 ('Netherlands_decoration_Netherlands','Netherlands Decoration','Netherlands','decoration','rare','Netherlands',false,ARRAY['#AE1C28','#21468B','#FF7F00']::text[],900),
 ('Netherlands_decoration_anim_Netherlands','Netherlands Animated Decoration','Netherlands','decoration','legendary','Netherlands',true,ARRAY['#AE1C28','#21468B','#FF7F00']::text[],1800),
 ('Netherlands_nameplate_Netherlands','Netherlands Name Plate','Netherlands','nameplate','rare','Netherlands',false,ARRAY['#AE1C28','#21468B','#FF7F00']::text[],750),
 ('Netherlands_banner_Netherlands','Netherlands Banner','Netherlands','banner','epic','Netherlands',false,ARRAY['#AE1C28','#21468B','#FF7F00']::text[],1500),
 ('Belgium_avatar_Belgium','Belgium Avatar','Belgium','avatar','common','Belgium',false,ARRAY['#111111','#FDDA24','#EF3340']::text[],600),
 ('Belgium_avatar_anim_Belgium','Belgium Animated Avatar','Belgium','avatar','epic','Belgium',true,ARRAY['#111111','#FDDA24','#EF3340']::text[],1200),
 ('Belgium_decoration_Belgium','Belgium Decoration','Belgium','decoration','rare','Belgium',false,ARRAY['#111111','#FDDA24','#EF3340']::text[],900),
 ('Belgium_decoration_anim_Belgium','Belgium Animated Decoration','Belgium','decoration','legendary','Belgium',true,ARRAY['#111111','#FDDA24','#EF3340']::text[],1800),
 ('Belgium_nameplate_Belgium','Belgium Name Plate','Belgium','nameplate','rare','Belgium',false,ARRAY['#111111','#FDDA24','#EF3340']::text[],750),
 ('Belgium_banner_Belgium','Belgium Banner','Belgium','banner','epic','Belgium',false,ARRAY['#111111','#FDDA24','#EF3340']::text[],1500),
 ('Japan_avatar_Japan','Japan Avatar','Japan','avatar','common','Japan',false,ARRAY['#BC002D','#FFFFFF','#7A001D']::text[],600),
 ('Japan_avatar_anim_Japan','Japan Animated Avatar','Japan','avatar','epic','Japan',true,ARRAY['#BC002D','#FFFFFF','#7A001D']::text[],1200),
 ('Japan_decoration_Japan','Japan Decoration','Japan','decoration','rare','Japan',false,ARRAY['#BC002D','#FFFFFF','#7A001D']::text[],900),
 ('Japan_decoration_anim_Japan','Japan Animated Decoration','Japan','decoration','legendary','Japan',true,ARRAY['#BC002D','#FFFFFF','#7A001D']::text[],1800),
 ('Japan_nameplate_Japan','Japan Name Plate','Japan','nameplate','rare','Japan',false,ARRAY['#BC002D','#FFFFFF','#7A001D']::text[],750),
 ('Japan_banner_Japan','Japan Banner','Japan','banner','epic','Japan',false,ARRAY['#BC002D','#FFFFFF','#7A001D']::text[],1500),
 ('USA_avatar_USA','USA Avatar','USA','avatar','common','USA',false,ARRAY['#3C3B6E','#B22234','#FFFFFF']::text[],600),
 ('USA_avatar_anim_USA','USA Animated Avatar','USA','avatar','epic','USA',true,ARRAY['#3C3B6E','#B22234','#FFFFFF']::text[],1200),
 ('USA_decoration_USA','USA Decoration','USA','decoration','rare','USA',false,ARRAY['#3C3B6E','#B22234','#FFFFFF']::text[],900),
 ('USA_decoration_anim_USA','USA Animated Decoration','USA','decoration','legendary','USA',true,ARRAY['#3C3B6E','#B22234','#FFFFFF']::text[],1800),
 ('USA_nameplate_USA','USA Name Plate','USA','nameplate','rare','USA',false,ARRAY['#3C3B6E','#B22234','#FFFFFF']::text[],750),
 ('USA_banner_USA','USA Banner','USA','banner','epic','USA',false,ARRAY['#3C3B6E','#B22234','#FFFFFF']::text[],1500),
 ('Mexico_avatar_Mexico','Mexico Avatar','Mexico','avatar','common','Mexico',false,ARRAY['#006847','#CE1126','#FFFFFF']::text[],600),
 ('Mexico_avatar_anim_Mexico','Mexico Animated Avatar','Mexico','avatar','epic','Mexico',true,ARRAY['#006847','#CE1126','#FFFFFF']::text[],1200),
 ('Mexico_decoration_Mexico','Mexico Decoration','Mexico','decoration','rare','Mexico',false,ARRAY['#006847','#CE1126','#FFFFFF']::text[],900),
 ('Mexico_decoration_anim_Mexico','Mexico Animated Decoration','Mexico','decoration','legendary','Mexico',true,ARRAY['#006847','#CE1126','#FFFFFF']::text[],1800),
 ('Mexico_nameplate_Mexico','Mexico Name Plate','Mexico','nameplate','rare','Mexico',false,ARRAY['#006847','#CE1126','#FFFFFF']::text[],750),
 ('Mexico_banner_Mexico','Mexico Banner','Mexico','banner','epic','Mexico',false,ARRAY['#006847','#CE1126','#FFFFFF']::text[],1500),
 ('Canada_avatar_Canada','Canada Avatar','Canada','avatar','common','Canada',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],600),
 ('Canada_avatar_anim_Canada','Canada Animated Avatar','Canada','avatar','epic','Canada',true,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],1200),
 ('Canada_decoration_Canada','Canada Decoration','Canada','decoration','rare','Canada',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],900),
 ('Canada_decoration_anim_Canada','Canada Animated Decoration','Canada','decoration','legendary','Canada',true,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],1800),
 ('Canada_nameplate_Canada','Canada Name Plate','Canada','nameplate','rare','Canada',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],750),
 ('Canada_banner_Canada','Canada Banner','Canada','banner','epic','Canada',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],1500),
 ('Croatia_avatar_Croatia','Croatia Avatar','Croatia','avatar','common','Croatia',false,ARRAY['#FF0000','#171796','#FFFFFF']::text[],600),
 ('Croatia_avatar_anim_Croatia','Croatia Animated Avatar','Croatia','avatar','epic','Croatia',true,ARRAY['#FF0000','#171796','#FFFFFF']::text[],1200),
 ('Croatia_decoration_Croatia','Croatia Decoration','Croatia','decoration','rare','Croatia',false,ARRAY['#FF0000','#171796','#FFFFFF']::text[],900),
 ('Croatia_decoration_anim_Croatia','Croatia Animated Decoration','Croatia','decoration','legendary','Croatia',true,ARRAY['#FF0000','#171796','#FFFFFF']::text[],1800),
 ('Croatia_nameplate_Croatia','Croatia Name Plate','Croatia','nameplate','rare','Croatia',false,ARRAY['#FF0000','#171796','#FFFFFF']::text[],750),
 ('Croatia_banner_Croatia','Croatia Banner','Croatia','banner','epic','Croatia',false,ARRAY['#FF0000','#171796','#FFFFFF']::text[],1500),
 ('Uruguay_avatar_Uruguay','Uruguay Avatar','Uruguay','avatar','common','Uruguay',false,ARRAY['#0038A8','#FCD116','#001E5C']::text[],600),
 ('Uruguay_avatar_anim_Uruguay','Uruguay Animated Avatar','Uruguay','avatar','epic','Uruguay',true,ARRAY['#0038A8','#FCD116','#001E5C']::text[],1200),
 ('Uruguay_decoration_Uruguay','Uruguay Decoration','Uruguay','decoration','rare','Uruguay',false,ARRAY['#0038A8','#FCD116','#001E5C']::text[],900),
 ('Uruguay_decoration_anim_Uruguay','Uruguay Animated Decoration','Uruguay','decoration','legendary','Uruguay',true,ARRAY['#0038A8','#FCD116','#001E5C']::text[],1800),
 ('Uruguay_nameplate_Uruguay','Uruguay Name Plate','Uruguay','nameplate','rare','Uruguay',false,ARRAY['#0038A8','#FCD116','#001E5C']::text[],750),
 ('Uruguay_banner_Uruguay','Uruguay Banner','Uruguay','banner','epic','Uruguay',false,ARRAY['#0038A8','#FCD116','#001E5C']::text[],1500),
 ('Switzerland_avatar_Switzerland','Switzerland Avatar','Switzerland','avatar','common','Switzerland',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],600),
 ('Switzerland_avatar_anim_Switzerland','Switzerland Animated Avatar','Switzerland','avatar','epic','Switzerland',true,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],1200),
 ('Switzerland_decoration_Switzerland','Switzerland Decoration','Switzerland','decoration','rare','Switzerland',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],900),
 ('Switzerland_decoration_anim_Switzerland','Switzerland Animated Decoration','Switzerland','decoration','legendary','Switzerland',true,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],1800),
 ('Switzerland_nameplate_Switzerland','Switzerland Name Plate','Switzerland','nameplate','rare','Switzerland',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],750),
 ('Switzerland_banner_Switzerland','Switzerland Banner','Switzerland','banner','epic','Switzerland',false,ARRAY['#FF0000','#FFFFFF','#A00000']::text[],1500),
 ('Norway_avatar_Norway','Norway Avatar','Norway','avatar','common','Norway',false,ARRAY['#BA0C2F','#00205B','#FFFFFF']::text[],600),
 ('Norway_avatar_anim_Norway','Norway Animated Avatar','Norway','avatar','epic','Norway',true,ARRAY['#BA0C2F','#00205B','#FFFFFF']::text[],1200),
 ('Norway_decoration_Norway','Norway Decoration','Norway','decoration','rare','Norway',false,ARRAY['#BA0C2F','#00205B','#FFFFFF']::text[],900),
 ('Norway_decoration_anim_Norway','Norway Animated Decoration','Norway','decoration','legendary','Norway',true,ARRAY['#BA0C2F','#00205B','#FFFFFF']::text[],1800),
 ('Norway_nameplate_Norway','Norway Name Plate','Norway','nameplate','rare','Norway',false,ARRAY['#BA0C2F','#00205B','#FFFFFF']::text[],750),
 ('Norway_banner_Norway','Norway Banner','Norway','banner','epic','Norway',false,ARRAY['#BA0C2F','#00205B','#FFFFFF']::text[],1500),
 ('wc26_avatar_GoldenTrophy','Golden Trophy Avatar','Golden Trophy','avatar','common',null,false,ARRAY['#FFB600','#FF8600','#7A4F00']::text[],700),
 ('wc26_avatar_anim_GoldenTrophy','Golden Trophy Animated Avatar','Golden Trophy','avatar','epic',null,true,ARRAY['#FFB600','#FF8600','#7A4F00']::text[],1300),
 ('wc26_decoration_GoldenTrophy','Golden Trophy Decoration','Golden Trophy','decoration','rare',null,false,ARRAY['#FFB600','#FF8600','#7A4F00']::text[],1000),
 ('wc26_decoration_anim_GoldenTrophy','Golden Trophy Animated Decoration','Golden Trophy','decoration','legendary',null,true,ARRAY['#FFB600','#FF8600','#7A4F00']::text[],1900),
 ('wc26_nameplate_GoldenTrophy','Golden Trophy Name Plate','Golden Trophy','nameplate','rare',null,false,ARRAY['#FFB600','#FF8600','#7A4F00']::text[],850),
 ('wc26_banner_GoldenTrophy','Golden Trophy Banner','Golden Trophy','banner','epic',null,false,ARRAY['#FFB600','#FF8600','#7A4F00']::text[],1600),
 ('wc26_avatar_ChampionsConfetti','Champions Confetti Avatar','Champions Confetti','avatar','common',null,false,ARRAY['#4000FF','#00E6C4','#FF2065']::text[],700),
 ('wc26_avatar_anim_ChampionsConfetti','Champions Confetti Animated Avatar','Champions Confetti','avatar','epic',null,true,ARRAY['#4000FF','#00E6C4','#FF2065']::text[],1300),
 ('wc26_decoration_ChampionsConfetti','Champions Confetti Decoration','Champions Confetti','decoration','rare',null,false,ARRAY['#4000FF','#00E6C4','#FF2065']::text[],1000),
 ('wc26_decoration_anim_ChampionsConfetti','Champions Confetti Animated Decoration','Champions Confetti','decoration','legendary',null,true,ARRAY['#4000FF','#00E6C4','#FF2065']::text[],1900),
 ('wc26_nameplate_ChampionsConfetti','Champions Confetti Name Plate','Champions Confetti','nameplate','rare',null,false,ARRAY['#4000FF','#00E6C4','#FF2065']::text[],850),
 ('wc26_banner_ChampionsConfetti','Champions Confetti Banner','Champions Confetti','banner','epic',null,false,ARRAY['#4000FF','#00E6C4','#FF2065']::text[],1600),
 ('wc26_avatar_HostUnite26','Host Unite 26 Avatar','Host Unite 26','avatar','common',null,false,ARRAY['#3C3B6E','#006847','#CE1126']::text[],700),
 ('wc26_avatar_anim_HostUnite26','Host Unite 26 Animated Avatar','Host Unite 26','avatar','epic',null,true,ARRAY['#3C3B6E','#006847','#CE1126']::text[],1300),
 ('wc26_decoration_HostUnite26','Host Unite 26 Decoration','Host Unite 26','decoration','rare',null,false,ARRAY['#3C3B6E','#006847','#CE1126']::text[],1000),
 ('wc26_decoration_anim_HostUnite26','Host Unite 26 Animated Decoration','Host Unite 26','decoration','legendary',null,true,ARRAY['#3C3B6E','#006847','#CE1126']::text[],1900),
 ('wc26_nameplate_HostUnite26','Host Unite 26 Name Plate','Host Unite 26','nameplate','rare',null,false,ARRAY['#3C3B6E','#006847','#CE1126']::text[],850),
 ('wc26_banner_HostUnite26','Host Unite 26 Banner','Host Unite 26','banner','epic',null,false,ARRAY['#3C3B6E','#006847','#CE1126']::text[],1600),
 ('wc26_avatar_PitchPerfect','Pitch Perfect Avatar','Pitch Perfect','avatar','common',null,false,ARRAY['#0C6B2E','#0A5526','#A6E5CA']::text[],700),
 ('wc26_avatar_anim_PitchPerfect','Pitch Perfect Animated Avatar','Pitch Perfect','avatar','epic',null,true,ARRAY['#0C6B2E','#0A5526','#A6E5CA']::text[],1300),
 ('wc26_decoration_PitchPerfect','Pitch Perfect Decoration','Pitch Perfect','decoration','rare',null,false,ARRAY['#0C6B2E','#0A5526','#A6E5CA']::text[],1000),
 ('wc26_decoration_anim_PitchPerfect','Pitch Perfect Animated Decoration','Pitch Perfect','decoration','legendary',null,true,ARRAY['#0C6B2E','#0A5526','#A6E5CA']::text[],1900),
 ('wc26_nameplate_PitchPerfect','Pitch Perfect Name Plate','Pitch Perfect','nameplate','rare',null,false,ARRAY['#0C6B2E','#0A5526','#A6E5CA']::text[],850),
 ('wc26_banner_PitchPerfect','Pitch Perfect Banner','Pitch Perfect','banner','epic',null,false,ARRAY['#0C6B2E','#0A5526','#A6E5CA']::text[],1600),
 ('wc26_avatar_NeonGoal','Neon Goal Avatar','Neon Goal','avatar','common',null,false,ARRAY['#4000FF','#00E6C4','#6640FF']::text[],700),
 ('wc26_avatar_anim_NeonGoal','Neon Goal Animated Avatar','Neon Goal','avatar','epic',null,true,ARRAY['#4000FF','#00E6C4','#6640FF']::text[],1300),
 ('wc26_decoration_NeonGoal','Neon Goal Decoration','Neon Goal','decoration','rare',null,false,ARRAY['#4000FF','#00E6C4','#6640FF']::text[],1000),
 ('wc26_decoration_anim_NeonGoal','Neon Goal Animated Decoration','Neon Goal','decoration','legendary',null,true,ARRAY['#4000FF','#00E6C4','#6640FF']::text[],1900),
 ('wc26_nameplate_NeonGoal','Neon Goal Name Plate','Neon Goal','nameplate','rare',null,false,ARRAY['#4000FF','#00E6C4','#6640FF']::text[],850),
 ('wc26_banner_NeonGoal','Neon Goal Banner','Neon Goal','banner','epic',null,false,ARRAY['#4000FF','#00E6C4','#6640FF']::text[],1600),
 ('wc26_avatar_StadiumLights','Stadium Lights Avatar','Stadium Lights','avatar','common',null,false,ARRAY['#101010','#FFB600','#4000FF']::text[],700),
 ('wc26_avatar_anim_StadiumLights','Stadium Lights Animated Avatar','Stadium Lights','avatar','epic',null,true,ARRAY['#101010','#FFB600','#4000FF']::text[],1300),
 ('wc26_decoration_StadiumLights','Stadium Lights Decoration','Stadium Lights','decoration','rare',null,false,ARRAY['#101010','#FFB600','#4000FF']::text[],1000),
 ('wc26_decoration_anim_StadiumLights','Stadium Lights Animated Decoration','Stadium Lights','decoration','legendary',null,true,ARRAY['#101010','#FFB600','#4000FF']::text[],1900),
 ('wc26_nameplate_StadiumLights','Stadium Lights Name Plate','Stadium Lights','nameplate','rare',null,false,ARRAY['#101010','#FFB600','#4000FF']::text[],850),
 ('wc26_banner_StadiumLights','Stadium Lights Banner','Stadium Lights','banner','epic',null,false,ARRAY['#101010','#FFB600','#4000FF']::text[],1600)
on conflict (code) do nothing;
